version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
  build:
    commands:
      - cd backend
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -o bin/bootstrap ./cmd/api/
      - cd bin && zip function.zip bootstrap

artifacts:
  base-directory: backend/bin
  files:
    - function.zip
