version: 0.2

phases:
  install:
    commands:
      - wget -qO /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      - wget -qO /tmp/terraform_SHA256SUMS https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_SHA256SUMS
      - cd /tmp && grep 'terraform_1.9.8_linux_amd64.zip' terraform_SHA256SUMS | sha256sum -c -
      - unzip -o /tmp/terraform.zip -d /usr/local/bin/
      - terraform --version
  build:
    commands:
      - cd infrastructure-terraform
      - terraform init -input=false
      - terraform apply -input=false -auto-approve
