version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - (cd frontend && npm ci)
  pre_build:
    commands:
      - (cd frontend && npm test -- --coverage --ci)
  build:
    commands:
      - (cd frontend && npm run build)
artifacts:
  base-directory: ./frontend/dist
  files:
    - "**/*"
